const authenticationOnCategory = require('./authenticationOnCategory'),
  authenticationOnTodo = require('./authenticationOnTodo'),
  authenticationOnTodoDetail = require('./authenticationOnTodoDetail'),
  authenticationOnFriendsList = require('./authenticationOnFriendsList'),
  authenticationOnAccount = require('./authenticationOnAccount'),
  validateUnAuthentication = require('./validateUnAuthentication'),
  loginHandler = require('./loginHandler'),
  signUpHandler = require('./signUpHandler'),
  validationHandler = require('./validationHandler'),
  logOutHandler = require('./logOutHandler'),
  resetPasswordEmailHandler = require('./resetPasswordEmailHandler'),
  resetPasswordHandler = require('./resetPasswordHandler'),
  setHashPasswordAndSalt = require('./setHashPasswordAndSalt'),
  accountDeleteHandler = require('./accountDeleteHandler'),
  allAccountsHandler = require('./allAccountsHandler'),
    assignCategoryHandler = require('./assignCategoryHandler');

module.exports = {
  authenticationOnCategory,
  authenticationOnTodo,
  authenticationOnTodoDetail,
  authenticationOnFriendsList,
  authenticationOnAccount,
  validateUnAuthentication,
  loginHandler,
  signUpHandler,
  validationHandler,
  resetPasswordEmailHandler,
  logOutHandler,
  resetPasswordHandler,
  setHashPasswordAndSalt,
  accountDeleteHandler,
  allAccountsHandler,
  assignCategoryHandler
};
